name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, Windows]
        python: ['2.7', '3.7']
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
    - run: pip install nox

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: nox + Windows + Python 2.7 workaround
      # This is in PATH, so nox resolves to it - but then subsequent steps fail
      run: rm C:/ProgramData/Chocolatey/bin/python2.7.exe
      if: matrix.os == 'Windows' && matrix.python == '2.7'

    - run: nox -s tests-${{ matrix.python }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - uses: pre-commit/action@v2.0.0
