name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, Windows]
        python: ['2.7', '3.7']
    steps:
    - uses: actions/checkout@master
      # Nox runner
    - uses: actions/setup-python@v2
    - run: python -m pip install nox
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: nox + Windows + Python 2.7 workaround
      # This is in PATH, so nox resolves to it - but then subsequent steps fail
      run: rm C:/ProgramData/Chocolatey/bin/python2.7.exe
      if: matrix.os == 'Windows' && matrix.python == '2.7'
    - run: nox -s tests-${{ matrix.python }}
